image: node:18

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - echo "Compiling the code..."

unit-test:
  stage: test
  script:
    - echo "Running unit tests..."


deploy:
  only:
    - tags
  stage: deploy
  script:
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
    - cat .npmrc
    - npm publish

