image: node:18

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - npm install
    - npm run test

publish:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_BRANCH == "master"'
      changes:
        - package.json
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+.*$/'
  script:
    # If no .npmrc is included in the repo, throw an error
    - |
      if [[ ! -f .npmrc ]]; then
          echo 'No .npmrc found! Please create a .npmrc file in your repository.'
          exit 1
      fi

    - NPM_PACKAGE_NAME=$(node -p "require('./package.json').name")
    - NPM_PACKAGE_VERSION=$(node -p "require('./package.json').version")

    # Check if the commit is on the "develop" or "master" branch or if the pipeline was triggered by a tag
    - |
      if [[ "$CI_COMMIT_BRANCH" == "develop" || "$CI_COMMIT_BRANCH" == "master" || "${CI_COMMIT_TAG}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+(-.*)?$" ]]; then
        npm publish
        echo "Published version ${NPM_PACKAGE_VERSION} of ${NPM_PACKAGE_NAME} to GitLab's NPM registry"
      fi