image: node:18

stages:
  #  - test
  - deploy

#test:
#  stage: test
#  script:
#    - npm install
#    - npm run test

publish:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+.*$/'
  script:
    # If no .npmrc is included in the repo, throw an error
    - |
      if [[ ! -f .npmrc ]]; then
          echo 'No .npmrc found! Please create a .npmrc file in your repository.'
          exit 1
      fi

    - NPM_PACKAGE_VERSION=$(node -p "require('./package.json').version")

    - echo "@gitlab-p2.autobid.de:registry=https://gitlab-p2.autobid.de/api/v4/projects/${CI_PROJECT_ID}/packages/npm/">>.npmrc
    - echo "\n //gitlab-p2.autobid.de/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}">>.npmrc


    # Check if the pipeline was triggered by a tag
    - |
      if [[ "${CI_COMMIT_TAG}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+(-.*)?$ ]]; then
        npm publish --verbose
        echo "Published version ${CI_COMMIT_TAG} new version to gitlab repository"
      fi